### ISSUE TITLE
PublicFox 2.0: Password not working

### ISSUE THREAD

**Issue by maverick74** [mrigor/publicfox#25]
I'm using PublicFox 2.0.
I set it to block options, about:config and about:addons configs with a password.
I enter the password (I'm sure it's the right one and that i'm typing it correctly) and press _**continue**_ but it simply does nothing

**Comment by martinho76** [comment]
I'm facing the same issue. After entering the password and hitting enter or pressing the continue button nothing happens - not even an error message... (Firefox 58.0.2 / Public Fox 2.0) Helped myself by by restarting firefox with disabled addOns (see #27). Deinstalled PublicFox and reinstalled again while entering the password hyper carefully again...facing same issue again. Please support - Thx

**Comment by maverick74** [comment]
It's been fixed in version 2.0.1.

Thanks

Closing.......

**Comment by davidd6** [comment]
I use publicfox in 2.0.1 in firefox. And have same problem. I write correct password and still don't have access. I try reinstall few time but same result. Firefox 84.0 64bit.

**Comment by maverick74** [comment]
@davidd6 
I'm currently not using the addon

But what about Firefox 91??? Does it work there?

Maybe an upgrade broke something...

**Comment by jdeus** [comment]
Sooo, is this project discontinued ?
